%dw 2.0
import * from dw::test::Asserts
---
payload must equalTo([
  {
    "ID": 1,
    "code1": "rree",
    "code2": "0001",
    "airlineName": "American Airlines",
    "toAirport": "LAX",
    "fromAirport": "MUA",
    "takeOffDate": |2016-01-20|,
    "price": 541,
    "planeType": "Boeing 787",
    "seatsAvailable": 0,
    "totalSeats": 200
  },
  {
    "ID": 2,
    "code1": "eefd",
    "code2": "0123",
    "airlineName": "American Airlines",
    "toAirport": "CLE",
    "fromAirport": "MUA",
    "takeOffDate": |2016-01-25|,
    "price": 300,
    "planeType": "Boeing 747",
    "seatsAvailable": 7,
    "totalSeats": 345
  },
  {
    "ID": 3,
    "code1": "ffee",
    "code2": "0192",
    "airlineName": "American Airlines",
    "toAirport": "LAX",
    "fromAirport": "MUA",
    "takeOffDate": |2016-01-20|,
    "price": 300,
    "planeType": "Boeing 777",
    "seatsAvailable": 0,
    "totalSeats": 300
  },
  {
    "ID": 4,
    "code1": "rree",
    "code2": "1000",
    "airlineName": "American Airlines",
    "toAirport": "CLE",
    "fromAirport": "MUA",
    "takeOffDate": |2016-01-20|,
    "price": 200,
    "planeType": "Boeing 737",
    "seatsAvailable": 5,
    "totalSeats": 150
  },
  {
    "ID": 5,
    "code1": "rree",
    "code2": "1093",
    "airlineName": "American Airlines",
    "toAirport": "SFO",
    "fromAirport": "MUA",
    "takeOffDate": |2016-02-11|,
    "price": 142,
    "planeType": "Boeing 737",
    "seatsAvailable": 1,
    "totalSeats": 150
  },
  {
    "ID": 6,
    "code1": "ffee",
    "code2": "1112",
    "airlineName": "American Airlines",
    "toAirport": "CLE",
    "fromAirport": "MUA",
    "takeOffDate": |2016-01-20|,
    "price": 954,
    "planeType": "Boeing 787",
    "seatsAvailable": 100,
    "totalSeats": 200
  },
  {
    "ID": 7,
    "code1": "eefd",
    "code2": "1994",
    "airlineName": "American Airlines",
    "toAirport": "SFO",
    "fromAirport": "MUA",
    "takeOffDate": |2016-01-01|,
    "price": 676,
    "planeType": "Boeing 777",
    "seatsAvailable": 0,
    "totalSeats": 300
  },
  {
    "ID": 8,
    "code1": "ffee",
    "code2": "2000",
    "airlineName": "American Airlines",
    "toAirport": "SFO",
    "fromAirport": "MUA",
    "takeOffDate": |2016-02-20|,
    "price": 300,
    "planeType": "Boeing 737",
    "seatsAvailable": 30,
    "totalSeats": 150
  },
  {
    "ID": 9,
    "code1": "eefd",
    "code2": "3000",
    "airlineName": "American Airlines",
    "toAirport": "SFO",
    "fromAirport": "MUA",
    "takeOffDate": |2016-02-01|,
    "price": 900,
    "planeType": "Boeing 737",
    "seatsAvailable": 0,
    "totalSeats": 150
  },
  {
    "ID": 10,
    "code1": "eefd",
    "code2": "4511",
    "airlineName": "American Airlines",
    "toAirport": "LAX",
    "fromAirport": "MUA",
    "takeOffDate": |2016-01-15|,
    "price": 900,
    "planeType": "Boeing 777",
    "seatsAvailable": 100,
    "totalSeats": 300
  },
  {
    "ID": 11,
    "code1": "rree",
    "code2": "4567",
    "airlineName": "American Airlines",
    "toAirport": "SFO",
    "fromAirport": "MUA",
    "takeOffDate": |2016-01-20|,
    "price": 456,
    "planeType": "Boeing 737",
    "seatsAvailable": 100,
    "totalSeats": 150
  }
])