name: Build, Test & Deploy to CloudHub 2.0

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:         
  test-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 17
      
      - name: Run MUnit Tests
        env:
          nexus_username: ${{ secrets.nexus_username }}
          nexus_password: ${{ secrets.nexus_password }}
          KEY: ${{ secrets.decryption_key }}
        run: |
          mvn test --settings .maven/settings.xml \
          -Dsecure.key="$KEY" \
          -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
          -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}"

      - name: Upload MUnit Test Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: munit-test-reports
          path: target/site/munit/coverage/

      - name: Build Application
        env:
          nexus_username: ${{ secrets.nexus_username }}
          nexus_password: ${{ secrets.nexus_password }}
          KEY: ${{ secrets.decryption_key }}
        run: |
          mvn clean package --settings .maven/settings.xml -DskipMunitTests \
          -Dsecure.key="$KEY" \
          -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
          -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}"

      - name: Stamp artifact file name with commit hash
        run: |
          artifactName1=$(ls target/*.jar | head -1)
          commitHash=$(git rev-parse --short "$GITHUB_SHA")
          artifactName2=$(ls target/*.jar | head -1 | sed "s/.jar/-$commitHash.jar/g")
          mv $artifactName1 $artifactName2
          echo "ARTIFACT_NAME=$(basename $artifactName2)" >> $GITHUB_ENV

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: target/*.jar
      
      - name: Publish to Exchange
        if: github.ref == 'refs/heads/main'
        env:
          nexus_username: ${{ secrets.nexus_username }}
          nexus_password: ${{ secrets.nexus_password }}
          KEY: ${{ secrets.decryption_key }}
        run: |
          mvn deploy --settings .maven/settings.xml -DskipMunitTests \
          -Dsecure.key="$KEY" \
          -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
          -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}"

      - name: Deploy to CloudHub 2.0
        if: github.ref == 'refs/heads/main'
        env:
          nexus_username: ${{ secrets.nexus_username }}
          nexus_password: ${{ secrets.nexus_password }}
          KEY: ${{ secrets.decryption_key }}
        run: |
          mvn deploy --settings .maven/settings.xml -DskipMunitTests -DmuleDeploy \
          -Dsecure.key="$KEY" \
          -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
          -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}" \
          -Dmule.artifact="target/${{ env.ARTIFACT_NAME }}"